services:
  app:
    build: ./docker/php
    container_name: app
    volumes:
      - .:/var/www/html
    environment:
      - PHP_DISPLAY_ERRORS=on
    depends_on:
      - mariadb

  webserver:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./uploads:/var/www/html/uploads
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mariadb:
    image: mariadb:10.11
    restart: always
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASS}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASS}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "${DB_PORT:-3306}:3306"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"  # Interface web
      - "1025:1025"  # Port SMTP utilisé par PHP

volumes:
  mariadb_data:
