services:
  app:
    build: ./docker/php
    container_name: camagru_app
    volumes:
      - .:/var/www/html
    environment:
      - PHP_DISPLAY_ERRORS=on
    depends_on:
      - mariadb
  
  webserver:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    
  mariadb:
    image: mariadb:10.11
    restart: always
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASS}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASS}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"

volumes:
  mariadb_data: