version: '3.8'

services:
  app:
    build: ./docker/php
    volumes:
      - .:/var/www/html
    environment:
      - PHP_DISPLAY_ERRORS=on
    depends_on:
      - db
  
  webserver:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: camagru
    volumes:
      - db_data:/var/lib/mysql

# ✅ Déclaration des volumes ici
volumes:
  db_data: